// <auto-generated />
using System;
using Azox.XTradeBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Azox.XTradeBot.Data.Migrations
{
    [DbContext(typeof(XTradeBotDbContext))]
    partial class XTradeBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Azox.XTradeBot.DomainModel.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnOrder(3);

                    b.Property<string>("Extended")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("LastUpdatedTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreationTime");

                    b.ToTable("Currency", (string)null);
                });

            modelBuilder.Entity("Azox.XTradeBot.DomainModel.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnOrder(3);

                    b.Property<string>("Extended")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("LastUpdatedTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreationTime");

                    b.ToTable("Exchange", (string)null);
                });

            modelBuilder.Entity("Azox.XTradeBot.DomainModel.ExchangePair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BaseAssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<int?>("ExchangeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("LastUpdatedTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<int>("PairType")
                        .HasColumnType("int");

                    b.Property<int?>("QuoteAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetId");

                    b.HasIndex("CreationTime");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("QuoteAssetId");

                    b.ToTable("ExchangePair", (string)null);
                });

            modelBuilder.Entity("Azox.XTradeBot.DomainModel.ExchangePair", b =>
                {
                    b.HasOne("Azox.XTradeBot.DomainModel.Currency", "BaseAsset")
                        .WithMany()
                        .HasForeignKey("BaseAssetId");

                    b.HasOne("Azox.XTradeBot.DomainModel.Exchange", "Exchange")
                        .WithMany("Pairs")
                        .HasForeignKey("ExchangeId");

                    b.HasOne("Azox.XTradeBot.DomainModel.Currency", "QuoteAsset")
                        .WithMany()
                        .HasForeignKey("QuoteAssetId");

                    b.Navigation("BaseAsset");

                    b.Navigation("Exchange");

                    b.Navigation("QuoteAsset");
                });

            modelBuilder.Entity("Azox.XTradeBot.DomainModel.Exchange", b =>
                {
                    b.Navigation("Pairs");
                });
#pragma warning restore 612, 618
        }
    }
}
